-- AlterEnum
BEGIN;
CREATE TYPE "Industry_new" AS ENUM ('BEAUTY_PERSONAL_CARE', 'FASHION_STYLE', 'HEALTH_WELLNESS', 'LIFESTYLE', 'FOOD_DRINK', 'TRAVEL_HOSPITALITY', 'PARENTING_FAMILY', 'TECH_DIGITAL', 'EDUCATION_KNOWLEDGE', 'BUSINESS_ENTREPRENEURSHIP', 'FINANCE_INVESTING', 'GAMING_ESPORTS', 'ENTERTAINMENT_MEDIA', 'ART_CREATIVITY', 'SPORTS', 'SUSTAINABILITY_ETHICS', 'PETS_ANIMALS', 'AUTOMOTIVE_MOBILITY', 'HOME_REAL_ESTATE', 'OTHER');
ALTER TABLE "Influencer" ALTER COLUMN "industries" TYPE "Industry_new"[] USING ("industries"::text::"Industry_new"[]);
ALTER TYPE "Industry" RENAME TO "Industry_old";
ALTER TYPE "Industry_new" RENAME TO "Industry";
DROP TYPE "public"."Industry_old";
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "Value_new" AS ENUM ('AUTHENTICITY', 'TRANSPARENCY', 'QUALITY', 'HONESTY', 'PROFESSIONALISM', 'CREATIVITY', 'EDUCATION', 'KNOWLEDGE_SHARING', 'SUSTAINABILITY', 'ETHICS', 'RESPONSIBILITY', 'MENTAL_HEALTH_BALANCE', 'SELF_CONFIDENCE', 'PERSONAL_GROWTH', 'INCLUSIVITY', 'DIVERSITY', 'BODY_POSITIVITY', 'NATURAL_BEAUTY', 'INNOVATION', 'LONG_TERM_PARTNERSHIPS', 'COMMUNITY', 'SUPPORT', 'COMMITMENT', 'CONSISTENCY', 'SOCIAL_RESPONSIBILITY', 'WORK_LIFE_BALANCE', 'PREMIUM_STANDARDS', 'ACCESSIBILITY', 'SUPPORTING_LOCAL_BRANDS', 'EMPATHY', 'OTHER');
ALTER TABLE "Influencer" ALTER COLUMN "values" TYPE "Value_new"[] USING ("values"::text::"Value_new"[]);
ALTER TYPE "Value" RENAME TO "Value_old";
ALTER TYPE "Value_new" RENAME TO "Value";
DROP TYPE "public"."Value_old";
COMMIT;
