/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivateInfluensersRouteImport } from './routes/_private/influensers'
import { Route as PrivateProfileUserIdRouteImport } from './routes/_private/profile.$userId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateInfluensersRoute = PrivateInfluensersRouteImport.update({
  id: '/influensers',
  path: '/influensers',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateProfileUserIdRoute = PrivateProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => PrivateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/influensers': typeof PrivateInfluensersRoute
  '/profile/$userId': typeof PrivateProfileUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/influensers': typeof PrivateInfluensersRoute
  '/profile/$userId': typeof PrivateProfileUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_private/influensers': typeof PrivateInfluensersRoute
  '/_private/profile/$userId': typeof PrivateProfileUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/influensers' | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/influensers' | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/auth'
    | '/_private/influensers'
    | '/_private/profile/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/influensers': {
      id: '/_private/influensers'
      path: '/influensers'
      fullPath: '/influensers'
      preLoaderRoute: typeof PrivateInfluensersRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/profile/$userId': {
      id: '/_private/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof PrivateProfileUserIdRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateInfluensersRoute: typeof PrivateInfluensersRoute
  PrivateProfileUserIdRoute: typeof PrivateProfileUserIdRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateInfluensersRoute: PrivateInfluensersRoute,
  PrivateProfileUserIdRoute: PrivateProfileUserIdRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
